import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, CheckCircle2, Bot, ChevronDown, ChevronUp, FileText, FileDown, FileType } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, AlignmentType, BorderStyle } from 'docx';

const ResultPanel = ({ data, onClose }) => {
  const [openSubtask, setOpenSubtask] = useState(null);
  const [exporting, setExporting] = useState(null);

  if (!data) return null;

  const totalCost = data.subtasks ? data.subtasks.reduce((sum, s) => sum + s.cost, 0) : 0;

  const formatDate = () => {
    return new Date().toLocaleString('en-US', {
      year: 'numeric', month: 'long', day: 'numeric',
      hour: '2-digit', minute: '2-digit', second: '2-digit'
    });
  };

  const exportPDF = async () => {
    setExporting('pdf');
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      const maxWidth = pageWidth - margin * 2;
      let y = 20;

      const addText = (text, size, isBold = false) => {
        doc.setFontSize(size);
        if (isBold) doc.setFont('helvetica', 'bold');
        else doc.setFont('helvetica', 'normal');
        const lines = doc.splitTextToSize(text, maxWidth);
        lines.forEach(line => {
          if (y > 275) {
            doc.addPage();
            y = 20;
          }
          doc.text(line, margin, y);
          y += size * 0.35 + 2;
        });
        doc.setFont('helvetica', 'normal');
      };

      const addSeparator = () => {
        if (y > 275) { doc.addPage(); y = 20; }
        y += 3;
        doc.setDrawColor(0, 0, 0);
        doc.line(margin, y, pageWidth - margin, y);
        y += 6;
      };

      doc.setTextColor(0, 0, 0);

      // Title
      addText('TASKFORCE - MISSION REPORT', 22, true);

      // Separator
      addSeparator();

      // Date & status
      addText(`Generated: ${formatDate()}`, 10);
      addText(`Status: ${data.status || 'COMPLETED'}`, 10);
      addText(`Total Cost: $${totalCost.toFixed(4)} USD  |  Agents Hired: ${data.subtasks?.length || 0}`, 10);
      y += 4;

      // Task Description
      addSeparator();
      addText('TASK DESCRIPTION', 14, true);
      addText(data.description || 'N/A', 11);
      y += 2;

      // Subtask Breakdown
      addSeparator();
      addText('AGENT BREAKDOWN', 14, true);

      if (data.subtasks) {
        data.subtasks.forEach((st, idx) => {
          if (y > 260) { doc.addPage(); y = 20; }
          y += 2;
          addText(`${idx + 1}. ${st.agent}`, 12, true);
          addText(`Task: ${st.description}`, 10);
          addText(`Cost: $${(st.cost || 0).toFixed(4)} USD  |  Reputation Change: ${st.reputation_change || 'N/A'}`, 10);
          const cleanOutput = (st.output || 'No output').replace(/\*\*/g, '').replace(/### /g, '');
          addText(`Output: ${cleanOutput}`, 10);
          y += 4;
        });
      }

      // Final Synthesis
      y += 2;
      addSeparator();
      addText('FINAL SYNTHESIZED OUTPUT', 14, true);
      const cleanFinalResult = (data.final_result || 'No output generated.').replace(/\*\*/g, '').replace(/### /g, '');
      addText(cleanFinalResult, 11);

      // Footer
      y = 280;
      doc.setFontSize(8);
      doc.text('Generated by TaskForce - Autonomous Agent Economy', margin, y);

      doc.save(`taskforce-mission-report-${Date.now()}.pdf`);
    } catch (err) {
      console.error('PDF export failed:', err);
    }
    setExporting(null);
  };

  const exportDOCX = async () => {
    setExporting('docx');
    try {
      const children = [];

      const addHeading = (text, level) => {
        children.push(
          new Paragraph({
            text,
            heading: level,
            spacing: { before: 300, after: 150 },
          })
        );
      };

      const addBody = (text, opts = {}) => {
        children.push(
          new Paragraph({
            children: [new TextRun({ text, size: 22, ...opts })],
            spacing: { after: 100 },
          })
        );
      };

      const addSeparator = () => {
        children.push(
          new Paragraph({
            spacing: { before: 150, after: 150 },
            borders: { bottom: { style: BorderStyle.SINGLE, size: 1, color: '000000' } },
          })
        );
      };

      // Title
      children.push(new Paragraph({
        children: [new TextRun({ text: 'TASKFORCE - MISSION REPORT', bold: true, size: 32, color: '000000' })],
        alignment: AlignmentType.CENTER,
        spacing: { after: 200 },
      }));

      addSeparator();

      // Metadata
      addBody(`Generated: ${formatDate()}`, { color: '000000', size: 20 });
      addBody(`Status: ${data.status || 'COMPLETED'}`, { color: '000000', size: 20 });
      addBody(`Total Cost: $${totalCost.toFixed(4)} USD  |  Agents Hired: ${data.subtasks?.length || 0}`, { color: '000000', size: 20 });

      // Task Description
      addSeparator();
      addHeading('Task Description', HeadingLevel.HEADING_2);
      addBody(data.description || 'N/A');

      // Subtask Breakdown
      addSeparator();
      addHeading('Agent Breakdown', HeadingLevel.HEADING_2);

      if (data.subtasks) {
        data.subtasks.forEach((st, idx) => {
          children.push(new Paragraph({
            children: [new TextRun({ text: `${idx + 1}. ${st.agent}`, bold: true, size: 24, color: '000000' })],
            spacing: { before: 200, after: 80 },
          }));
          addBody(`Task: ${st.description}`, { color: '000000' });
          addBody(`Cost: $${(st.cost || 0).toFixed(4)} USD  |  Reputation Change: ${st.reputation_change || 'N/A'}`, { color: '000000' });
          const cleanOutputDocx = (st.output || 'No output').replace(/\*\*/g, '').replace(/### /g, '');
          addBody(`Output: ${cleanOutputDocx}`, { color: '000000' });
        });
      }

      // Final Synthesis
      addSeparator();
      addHeading('Final Synthesized Output', HeadingLevel.HEADING_2);
      const cleanFinalResultDocx = (data.final_result || 'No output generated.').replace(/\*\*/g, '').replace(/### /g, '');
      addBody(cleanFinalResultDocx, { color: '000000' });

      // Footer
      children.push(new Paragraph({ spacing: { before: 400 } }));
      children.push(new Paragraph({
        children: [new TextRun({ text: 'Generated by TaskForce - Autonomous Agent Economy', size: 16, color: '000000', italics: true })],
        alignment: AlignmentType.CENTER,
      }));

      const doc = new Document({
        title: 'TaskForce Mission Report',
        description: 'Autonomous Agent Economy Mission Report',
        creator: 'TaskForce',
        sections: [{ children }],
      });

      const blob = await Packer.toBlob(doc);
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `taskforce-mission-report-${Date.now()}.docx`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('DOCX export failed:', err);
    }
    setExporting(null);
  };

  return (
    <motion.div
      initial={{ y: '100%' }}
      animate={{ y: 0 }}
      exit={{ y: '100%' }}
      transition={{ type: 'spring', damping: 25, stiffness: 120 }}
      className="absolute bottom-0 left-0 right-0 h-[92dvh] sm:h-[85vh] lg:h-[65vh] bg-space border-t border-primary/30 shadow-[0_-10px_40px_rgba(99,102,241,0.1)] z-50 flex flex-col safe-area-bottom"
    >
      {/* Header */}
      <div className="p-3 sm:p-4 border-b border-white/10 flex items-start sm:items-center justify-between gap-3 bg-white/[0.02] shrink-0">
        <div className="flex items-start sm:items-center gap-3 min-w-0">
          <div className="bg-success/20 p-2 rounded text-success border border-success/30 shrink-0">
            <CheckCircle2 className="w-5 h-5" />
          </div>
          <div className="min-w-0">
            <h2 className="text-base sm:text-lg font-bold text-white tracking-wide">
              MISSION ACCOMPLISHED
            </h2>
            <div className="flex flex-wrap items-center gap-x-4 gap-y-1 mt-1 text-xs text-gray-400 font-mono">
              <span>
                Total Cost: <span className="text-warning">{totalCost.toFixed(4)} AVAX</span>
              </span>
              <span>
                Agents Hired: <span className="text-primary">{data.subtasks?.length || 0}</span>
              </span>
            </div>
          </div>
        </div>
        <div className="flex items-center gap-1 sm:gap-2 shrink-0">
          <button
            onClick={exportPDF}
            disabled={exporting !== null}
            className="p-2 hover:bg-white/10 rounded text-gray-400 hover:text-primary transition-colors disabled:opacity-40"
            title="Export as PDF"
          >
            {exporting === 'pdf' ? (
              <span className="w-5 h-5 block border-2 border-primary border-t-transparent rounded-full animate-spin" />
            ) : (
              <FileDown className="w-5 h-5" />
            )}
          </button>
          <button
            onClick={exportDOCX}
            disabled={exporting !== null}
            className="p-2 hover:bg-white/10 rounded text-gray-400 hover:text-secondary transition-colors disabled:opacity-40"
            title="Export as Word"
          >
            {exporting === 'docx' ? (
              <span className="w-5 h-5 block border-2 border-secondary border-t-transparent rounded-full animate-spin" />
            ) : (
              <FileType className="w-5 h-5" />
            )}
          </button>
          <button onClick={onClose} className="p-2 hover:bg-white/10 rounded text-gray-400 hover:text-white transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>
      </div>

      <div className="flex-1 flex flex-col lg:flex-row overflow-hidden min-h-0">
        {/* Left: Subtask Breakdown */}
        <div className="w-full lg:w-1/3 border-b lg:border-b-0 lg:border-r border-white/10 overflow-y-auto p-4 bg-black/40 max-h-[38vh] lg:max-h-none shrink-0 lg:shrink">
          <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-widest mb-4">Subtask Breakdown</h3>
          <div className="space-y-3">
            {data.subtasks && data.subtasks.map((st, idx) => (
              <div key={idx} className="border border-white/10 rounded bg-white/5 overflow-hidden">
                <div 
                  className="p-3 flex items-center justify-between cursor-pointer hover:bg-white/10"
                  onClick={() => setOpenSubtask(openSubtask === idx ? null : idx)}
                >
                  <div className="flex items-center gap-3">
                    <Bot className="w-4 h-4 text-primary" />
                    <span className="text-sm font-medium text-gray-200">{st.agent}</span>
                  </div>
                  {openSubtask === idx ? <ChevronUp className="w-4 h-4 text-gray-500" /> : <ChevronDown className="w-4 h-4 text-gray-500" />}
                </div>
                
                <AnimatePresence>
                  {openSubtask === idx && (
                    <motion.div 
                      initial={{ height: 0 }}
                      animate={{ height: "auto" }}
                      exit={{ height: 0 }}
                      className="overflow-hidden border-t border-white/10"
                    >
                      <div className="p-3 space-y-2 bg-black/20">
                        <p className="text-xs text-gray-400"><span className="text-gray-500">Task:</span> {st.description}</p>
                        <div className="flex items-center gap-4 text-[10px] font-mono">
                          <span className="text-warning">Cost: {st.cost.toFixed(4)} AVAX</span>
                          <span className="text-success">Reputation: {st.reputation_change}</span>
                        </div>
                        <div className="mt-2 text-xs text-gray-300 font-mono bg-black p-2 rounded border border-white/5 max-h-32 overflow-y-auto whitespace-pre-wrap">
                          {st.output}
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            ))}
          </div>
        </div>

        {/* Right: Synthesis */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-6 lg:p-8 relative bg-grid-pattern min-h-0">
          <div className="absolute inset-0 bg-space/90" />
          <div className="relative z-10 max-w-3xl mx-auto">
            <h3 className="text-xs font-semibold text-primary uppercase tracking-widest mb-4 sm:mb-6 flex items-center gap-2">
              <FileText className="w-4 h-4 shrink-0" /> Final Synthesized Output
            </h3>
            <div className="prose prose-sm sm:prose-base prose-invert prose-p:text-gray-300 prose-headings:text-white border-l-2 border-primary/50 pl-4 sm:pl-6 py-2 break-words">
              {data.final_result ? (
                <div dangerouslySetInnerHTML={{ __html: data.final_result.replace(/\*\*/g, '').replace(/### /g, '').replace(/\n/g, '<br/>') }} />
              ) : (
                <p className="text-gray-500 italic">No output generated.</p>
              )}
            </div>
            
            <div className="mt-6 sm:mt-10 flex items-center gap-4">
              <button
                onClick={onClose}
                className="w-full sm:w-auto px-6 py-2.5 sm:py-2 bg-white/10 hover:bg-white/20 text-white text-xs font-bold tracking-widest uppercase transition-all rounded text-center"
              >
                Deploy Another Task
              </button>
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
};

export default ResultPanel;
